site_name: anpr-ocr
site_author: anpr-ocr contributors
site_description: anpr-ocr license plate detection and recognition.
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Custom Models: custom_models.md
  - Contributing: contributing.md
  - Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ anpr_ocr ]
          load_external_modules: true
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            show_category_heading: true
            docstring_options:
              ignore_init_summary: true
            show_signature: true
            show_source: true
            heading_level: 2
            show_root_full_path: false
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      title: Page contents
